version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - db_config.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup_file.sql:/docker-entrypoint-initdb.d/backup_file.sql
    ports:
      - "3306:3306"
    networks:
      - opencart

  opencart:
    build:
      dockerfile: Dockerfile
    container_name: opencart
    restart: always
    volumes:
      - opencart_data:/var/www/html
    depends_on:
      - mysql
    ports:
      - "80:80"
    networks:
      - opencart

volumes:
  mysql_data:
  opencart_data:

networks:
  opencart:
    driver: bridge
