version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - db_config.env
    volumes:
      - mysql_data:/mysql
    ports:
      - '3306:3306'
    networks:
      - opencart
  opencart:
    image: bitnami/opencart:latest
    container_name: opencart
    ports:
      - '80:8080'
      - '443:8443'
    env_file:
      - opencart_config.env
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mysql
    networks:
      - opencart
volumes:
  mysql_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
networks:
  opencart:
    driver: bridge
